[package]
name = "path-tiny"
version = "0.1.0"
authors = ["Chylli <chylli@163.com>"]
description = "Toos for path & file in Rust"
repository = "https://github.com/chylli/path-tiny"
keywords = ["path", "tools"]
license = "MIT"

[dependencies]
regex = "0.2.10"
lazy_static = "1.0.0"
